import 'dart:async';
import 'package:aqueduct/aqueduct.dart';   

class Migration1 extends Migration { 
  @override
  Future upgrade() async {
   		database.createTable(SchemaTable("tblUser", [SchemaColumn("idUsers", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("name", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("lastName", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("birDate", ManagedPropertyType.datetime, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("password", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("email", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: true)]));
		database.createTable(SchemaTable("tblUserType", [SchemaColumn("idUsersType", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("description", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: true)]));
		database.createTable(SchemaTable("tblCourse", [SchemaColumn("idCourse", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("name", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("description", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false)]));
		database.createTable(SchemaTable("tblSchedule", [SchemaColumn("idSchedule", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false)]));
		database.createTable(SchemaTable("tblDelivery", [SchemaColumn("idDelivery", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("file", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("datDelivery", ManagedPropertyType.datetime, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false)]));
		database.createTable(SchemaTable("tblCommentAdvertisement", [SchemaColumn("idCommentAdvertisement", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("Comment", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("datComAdvertisement", ManagedPropertyType.datetime, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false)]));
		database.createTable(SchemaTable("tblActivities", [SchemaColumn("id", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("activity", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("description", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("datActivity", ManagedPropertyType.datetime, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false)]));
		database.createTable(SchemaTable("tblAdvertisement", [SchemaColumn("idAdvertisement", ManagedPropertyType.integer, isPrimaryKey: true, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("notice", ManagedPropertyType.string, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false),SchemaColumn("datAdvertisement", ManagedPropertyType.datetime, isPrimaryKey: false, autoincrement: false, isIndexed: false, isNullable: false, isUnique: false)]));
		database.addColumn("tblUser", SchemaColumn.relationship("idType", ManagedPropertyType.integer, relatedTableName: "tblUserType", relatedColumnName: "idUsersType", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblCourse", SchemaColumn.relationship("idTeacher", ManagedPropertyType.integer, relatedTableName: "tblUser", relatedColumnName: "idUsers", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblSchedule", SchemaColumn.relationship("idStudent", ManagedPropertyType.integer, relatedTableName: "tblUser", relatedColumnName: "idUsers", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblSchedule", SchemaColumn.relationship("idCourse", ManagedPropertyType.integer, relatedTableName: "tblCourse", relatedColumnName: "idCourse", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblDelivery", SchemaColumn.relationship("idStudent", ManagedPropertyType.integer, relatedTableName: "tblUser", relatedColumnName: "idUsers", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblDelivery", SchemaColumn.relationship("idActivity", ManagedPropertyType.integer, relatedTableName: "tblActivities", relatedColumnName: "id", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblCommentAdvertisement", SchemaColumn.relationship("idAdvertisement", ManagedPropertyType.integer, relatedTableName: "tblAdvertisement", relatedColumnName: "idAdvertisement", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblCommentAdvertisement", SchemaColumn.relationship("idUser", ManagedPropertyType.integer, relatedTableName: "tblUser", relatedColumnName: "idUsers", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblActivities", SchemaColumn.relationship("idCourse", ManagedPropertyType.integer, relatedTableName: "tblCourse", relatedColumnName: "idCourse", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
		database.addColumn("tblAdvertisement", SchemaColumn.relationship("idCourse", ManagedPropertyType.integer, relatedTableName: "tblCourse", relatedColumnName: "idCourse", rule: DeleteRule.nullify, isNullable: true, isUnique: true));
  }
  
  @override
  Future downgrade() async {}
  
  @override
  Future seed() async {}
}
    